<!DOCTYPE html>
<!--
Created using JS Bin
http://jsbin.com

Copyright (c) 2025 by anonymous (http://jsbin.com/wixudewoxo/3/edit)

Released under the MIT license: http://jsbin.mit-license.org
-->
<meta name="robots" content="noindex">
<html lang="km">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>គេហទំព័ររបស់ខ្ញុំ</title>
    <link rel="stylesheet" href="styles.css">
<style id="jsbin-css">
body {
    background-color: black; /* កំណត់ background color ខ្មៅ */
    color: white; /* កំណត់ text color ស */
    font-family: Arial, sans-serif; /* កំណត់ font */
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh; /* ធ្វើអោយ content នៅកណ្តាលអេក្រង់ */
    margin: 0; /* លុប margin default */
}

.content {
    font-size: 24px; /* កំណត់ទំហំអក្សរ */
    text-align: center; /* ធ្វើអោយអត្ថបទនៅកណ្តាល */
}
</style>
</head>
<body>
    <div class="content">
        អាយ៉ាណាគេពុងមើលយ៉ាងអែង
    </div>
</body>
</html>
